// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCmGRycCF-Ojwt7Q3RJ_xtTCs_HVyFRFQ0',
    appId: '1:649538803538:web:b78038325faf9fd99ecc8b',
    messagingSenderId: '649538803538',
    projectId: 'mybonus-multimedia',
    authDomain: 'mybonus-multimedia.firebaseapp.com',
    storageBucket: 'mybonus-multimedia.firebasestorage.app',
    measurementId: 'G-DY4P5B6N91',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDcspEFF6u9zS5YXh7o7jXPcqCsDKgar3c',
    appId: '1:649538803538:android:213f2c2cbe0431129ecc8b',
    messagingSenderId: '649538803538',
    projectId: 'mybonus-multimedia',
    storageBucket: 'mybonus-multimedia.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDkeEtarhme9NY4AokeShgGZEbboRK695g',
    appId: '1:649538803538:ios:34e9c535818d187f9ecc8b',
    messagingSenderId: '649538803538',
    projectId: 'mybonus-multimedia',
    storageBucket: 'mybonus-multimedia.firebasestorage.app',
    iosBundleId: 'com.bonusmultimedia.mybonus',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDkeEtarhme9NY4AokeShgGZEbboRK695g',
    appId: '1:649538803538:ios:ebe09c292001a0619ecc8b',
    messagingSenderId: '649538803538',
    projectId: 'mybonus-multimedia',
    storageBucket: 'mybonus-multimedia.firebasestorage.app',
    iosBundleId: 'com.example.yourappname',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCmGRycCF-Ojwt7Q3RJ_xtTCs_HVyFRFQ0',
    appId: '1:649538803538:web:7bb8494addcfccc19ecc8b',
    messagingSenderId: '649538803538',
    projectId: 'mybonus-multimedia',
    authDomain: 'mybonus-multimedia.firebaseapp.com',
    storageBucket: 'mybonus-multimedia.firebasestorage.app',
    measurementId: 'G-Q9NRNNTNJQ',
  );

}